### ISSUE TITLE
PostCSS icon not applied to `postcss.config.js`

### ISSUE THREAD

**Issue by SnO2WMaN** [file-icons/vscode#82]
The `postcss.config.js`, `mjs` and `cjs` are missing from the `fileNames` of `file-icons-icon-theme.json`, and the icons are not reflected correctly. 
I was going to fix this problem, but I have a feeling that `scripts/import-fixes.json` is probably not used anymore and I coundn't figure out that how to build JSON. Could  you please fix this problem?

![2022 03 27_12 41 22](https://user-images.githubusercontent.com/15155608/161450961-111b4643-7c6a-4e60-b1a5-a58c619eea1e.png)

**Comment by Alhadis** [comment]
Hey @SnO2WMaN,

> I was going to fix this problem, but I have a feeling that `scripts/import-fixes.json` is probably not used anymore

Your hunch is correct. The script that imports filetypes from the Atom package is undergoing a full rewrite, one that'll render the `import-fixes.json` file (mostly) obsolete. Once it's finished, it'll solve several issues related to the old import script, including yours.

I meant to have this finished ages ago, but I've been incredibly slack lately. 😞 I'm making a renewed effort to get this finished ASAP.

**Comment by SnO2WMaN** [comment]
To be honest, the code for the JSON generation part is too complicated for me , and I have been rewriting the generation part in deno, but it is very difficult to port it with compatibility (some packages cannot be brought to deno, such as less and genex), and I am about to give up on it. 

Anyway, thanks for your quick reply.

**Comment by Alhadis** [comment]
Rewriting [`scripts/update.mjs`](https://github.com/file-icons/vscode/blob/378ac3dfd01c17a991f9283dc6fa5531f571e43a/scripts/update.mjs), you mean? Erh, that's the part I'm still working on (meaning it's still unfinished). So, yeah, I wouldn't recommend rewriting a rewrite. 😜

(FYI, even this new import script is a temporary solution until I have a more unified and intuitive workflow established… Hence, we won't be using it forever)

> I have been rewriting the generation part in deno

Just curious, why would you be using Deno instead of Node.js?

**Comment by SnO2WMaN** [comment]
> Just curious, why would you be using Deno instead of Node.js?

No particular reason, I was just interested in my recent.

**Comment by Alhadis** [comment]
Fixed in b6439ae.
